### ISSUE TITLE
请问如何处理model加载后无法识别的问题？

### ISSUE THREAD

**Issue by pengwenwu** [Tilogorn/codeigniter-vanilla-phpstan#1]
请问样例中的这个报错，是如何解决的？

Access to an undefined property Welcome::$WelcomeModel.

**Comment by Tilogorn** [comment]
This repository is not intended to work. I updated the README.md accordingly.

> This is repository is not intended to solve the existing conflicts between PHPStan and CodeIgniter but to be a playground for the issues created in both projects (see https://github.com/phpstan/phpstan/issues/2422 and https://github.com/bcit-ci/CodeIgniter/issues/5763)
